default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: captura_development
  host: localhost
  port: 5432
  
test:
  <<: *default
  database: captura_test


production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
